// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF2h22RSXjr3eUanuw5XxbZVNyuGGb3jU',
    appId: '1:987692678226:web:e2d43410eb03bda261338b',
    messagingSenderId: '987692678226',
    projectId: 'project-flutter-13bd5',
    authDomain: 'project-flutter-13bd5.firebaseapp.com',
    storageBucket: 'project-flutter-13bd5.firebasestorage.app',
    measurementId: 'G-56K95HSKYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VYV8AL2CB4gAS3Vjdcvctxm_a4vO8fs',
    appId: '1:987692678226:android:2f96d132d5e201aa61338b',
    messagingSenderId: '987692678226',
    projectId: 'project-flutter-13bd5',
    storageBucket: 'project-flutter-13bd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAEBzAraNUj_fhT7GpoKArL2jNtYL8M40',
    appId: '1:987692678226:ios:657b61ae3825e2f561338b',
    messagingSenderId: '987692678226',
    projectId: 'project-flutter-13bd5',
    storageBucket: 'project-flutter-13bd5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAEBzAraNUj_fhT7GpoKArL2jNtYL8M40',
    appId: '1:987692678226:ios:657b61ae3825e2f561338b',
    messagingSenderId: '987692678226',
    projectId: 'project-flutter-13bd5',
    storageBucket: 'project-flutter-13bd5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF2h22RSXjr3eUanuw5XxbZVNyuGGb3jU',
    appId: '1:987692678226:web:f65cefb6687760b361338b',
    messagingSenderId: '987692678226',
    projectId: 'project-flutter-13bd5',
    authDomain: 'project-flutter-13bd5.firebaseapp.com',
    storageBucket: 'project-flutter-13bd5.firebasestorage.app',
    measurementId: 'G-86CZN1BKDD',
  );
}
